services:
  postgres:
    image: postgres:15
    container_name: amesie_postgres
    environment:
      POSTGRES_USER: amesie_user
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: amesie_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: .
    container_name: amesie_backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://amesie_user:strongpassword@postgres:5432/amesie_db
      MISTRAL_API_KEY: wOY8Kczkw2Byk5LxIYM1VUOt94V9ZAYV
      REDIS_HOST: redis
      REDIS_PORT: 6379
    restart: unless-stopped

volumes:
  postgres_data:
